Create applicationTrigger.py
xebialabs-community/xlr-xldeploy-plugin pull request #70
Opened 2017-07-18 13:27 UTC by istairbn

Underlying code, no changes to the Synthetic. 

Allows an XL Release Template to be triggered if a new Application Version is added to XL Deploy. 
Useful for triggering processes where the pipeline does not start in XL Release (for example, starts from a CI build agent).

2017-07-18 14:14 UTC, jdewinne commented on src/main/resources/xlr_xldeploy/applicationTrigger.py
> +except:
check_ci_exist has a throw_on_fail option

2017-07-18 14:14 UTC, jdewinne commented
Shouldn't this also include some changes in the `synthetic.xml`

2017-07-18 14:21 UTC, istairbn commented on src/main/resources/xlr_xldeploy/applicationTrigger.py
> +except:
Valid point - setting that to True. That means we can cut some of the fat off.

2017-07-18 14:24 UTC, istairbn commented
There are synthetic changes on my fork. 

However, every time this repo changes the synthetic, I can no longer merge updates back in to my fork. The changes don't match brilliantly well because I have so many extra functions. Ideally, I'd like to know which of the extra features you want (if any) and do a single fix rather than keep patching and re-pulling the synthetic.

2017-07-26 16:13 UTC, jdewinne requested changes
I think if you can make that last change, we're ready to merge this into master

2017-07-26 16:13 UTC, jdewinne commented on src/main/resources/xlr_xldeploy/applicationTrigger.py
> +packageId = xld_client.get_latest_package_version(applicationId)
Can we refactor `packageId` into `package_id`?

2017-09-25 11:24 UTC, closed without merging